# -*- coding: utf-8 -*-
"""project2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TYOMgOBLQygvC70XfVsjRXKde-TKsGg9

# Desafio: 

Você trabalha em uma grande empresa de Cartão de Crédito e o diretor da empresa percebeu que o número de clientes que cancelam seus cartões tem aumentado significativamente, causando prejuízos enormes para a empresa

O que fazer para evitar isso? Como saber as pessoas que têm maior tendência a cancelar o cartão?

# O que temos:

Temos 1 base de dados com informações dos clientes, tanto clientes atuais quanto clientes que cancelaram o cartão

Download da Base de Dados: https://drive.google.com/file/d/1c0F7BDwvOZ9NnIj3tUANuvmp_jRYsh31/view?usp=sharing

Referência: https://www.kaggle.com/sakshigoyal7/credit-card-customers

- Passo 1: Importar a Base de Dados 
- Passo 2: Tratamento a Base de Dados
    - Excluir/Corrigir linhas e colunas vazias
    - Ajeitar as colunas importadas
    - Excluir colunas inúteis
- Passo 3: Analisar a Base de Dados
    - Queremos descobrir os principais motivos de cancelamento de cartão

Passo 1: Importar a Base de Dados
"""

import pandas as pd

tabela_clientes = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/ClientesBanco.csv", encoding="latin1")
tabela_clientes = tabela_clientes.drop("CLIENTNUM", axis=1) # excluindo coluna 
display(tabela_clientes)

"""Passo 2: Tratamento da Base de Dados"""

tabela_clientes = tabela_clientes.dropna() # exclui as linhas que têm itens vazios

display(tabela_clientes.info())
display(tabela_clientes.describe())

"""Passo 3: Analisar os Dados
 - Queremos descobrir o motivo do clientes cancelarem
"""

display(tabela_clientes["Categoria"].value_counts())
display(tabela_clientes["Categoria"].value_counts(normalize=True))

"""Objetivo: Analisar o 80/20 - Regra de Pareto

Olhar todas as características dos clientas e descobrir os PRINCIPAIS MOTIVOS de cancelamento
"""

import plotly.express as px

for coluna in tabela_clientes:
  # Passo 1 - criar a gráfico 
  fig = px.histogram(tabela_clientes, x=coluna, color="Categoria")
  # Passo 2 - exibir a gráfico
  fig.show()

"""Analisando os gráficos:


1.   Quase todos os clientes que cancelaram são da categoria Blue
2.   Quanto mais um cliente entra em contato o banco, maior a chance dele cancelar  
  - Plano de Ação: Analisar o motivo do contato/Tratar os clientes que mais entraram em contato com o banco 
3.   Me parece que quem usa pouco o limite, cancela o cartão
     - Com mais de 80 transações o cliente não cancela mais o cartão
     - Clientes com menos de 60 transações são muito criticos
     - A mesma coisa acontece com a quantidade de transações




"""